### ISSUE TITLE
Remote Images

### ISSUE THREAD

**Issue by tomgallagher** [tsayen/dom-to-image#22] opened 2016-03-03 13:23 UTC
Hi

I've just started to use this library - very helpful.

Rendering dom with some remote image sources in it. Getting:

`XMLHttpRequest cannot load https://{bucket}.s3.amazonaws.com/uploads/North_face.jpg. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '{me}' is therefore not allowed access.

I've checked the CORS settings on my bucket. All OK.

Curl from the same terminal, 200 OK.

Not quite sure where to go now. Where in the code do you set the request headers? Maybe that's where I'll start.

Thanks 

Tom

**Comment by tsayen** [comment] 2016-03-03 13:32
Hi, thanks for the report. I suppose the problem is somewhere around [this code](https://github.com/tsayen/dom-to-image/blob/master/src/dom-to-image.js#L363).

**Comment by tomgallagher** [comment] 2016-03-03 14:12
Hi Anatolli

 

Thanks for getting back.

 

I think with Amazon S3 and the XMLHttpRequest(); I'm facing two potential
problems.

 

Firstly I need to add an origin header to the request. Thanks very much for
pointing out where this happens in the code.

 

Then I fear I might run into a second problem, which is that Amazon S3,
according to some reports, does not respond with a
Access-Control-Allow-Origin

 

Even if you send the origin header! I'll come back to you with more details.

 

Tom

 

  _____

**Comment by tsayen** [comment] 2016-03-03 14:32
If that will solve your problem, I think we can add required header to the request (I assume that change doesn't break other cases). Let me know when you have some more info

**Comment by tomgallagher** [comment] 2016-03-03 14:39
I'm just trying that at the moment with

 

request.open('GET', url, true);

var originURL = window.location.origin;

request.setRequestHeader('Origin', originURL);

request.send();

 

insert at around line 370 of your code.

 

It's currently saying that: Refused to set unsafe header "Origin"

 

Still looking into it.

  _____

**Comment by tomgallagher** [comment] 2016-03-03 16:40
OK this is a well-known problem with XMLHttpRequest and Amazon S3.

 

I've been through a whole host of potential solutions and I've got nowhere.

 

The browser should be adding the Origin header when it makes the request, it
is a restricted header anyway, it cannot be added in the code.

 

I am unable at the moment to customise S3 to send the
Access-Control-Allow-Origin header as required by XMLHttpRequest.

 

Your code now raises an error 'cannot fetch resource' but there is still an
uncaught exception (in promise) so the dom node does not download. I'll
check with something that has no images in it later on.

 

Thanks

 

  

 

  _____

**Comment by tomgallagher** [comment] 2016-03-03 16:52
OK it's now resolved and I have no idea why. I went away and came back, it
worked.

 

All I can think is that the changes I made to the CORS policy on Amazon S3
took quite a long time to propagate.

 

Your code was never the problem and the results are great. Thanks for your
time.

 

  _____

**Comment by tomgallagher** [comment] 2016-03-04 09:29
Still having this problem intermittently.

**Comment by tsayen** [comment] 2016-03-04 09:44
Hmm, what do you think, is there a change we could make to the lib that would solve the issue? I'm thinking about "relaxing" resource fetching in general, so that unavailable (in any manner) resource does not break whole rendering process, but the user only gets, say, an error message on the console

**Comment by tomgallagher** [comment] 2016-03-04 10:11
If you were to render without resources, that would probably be a more
manageable experience. Perhaps replace the image with the error message?  If
the page rendered with white gaps saying 'Access Headers.." Etc

 

The problem with a strict rule when dealing with the infinite variety of
doms is that it cannot work every time. So you have to have a more
manageable failure process, in my experience.

 

 

 

  _____

**Comment by tomgallagher** [comment] 2016-03-04 12:15
By the way, I meant to ask you, how do you deal with pixel resolution? 

 

So at some stage when you're constructing the output, whether blob or PNG,
you have to make a decision about sizes, I'd imagine.

 

  _____

**Comment by tsayen** [comment] 2016-03-04 12:28
I just get the computed size of the original node, it's [here](
https://github.com/tsayen/dom-to-image/blob/master/src/dom-to-image.js#L42)

**Comment by tomgallagher** [comment] 2016-03-04 23:10
So users viewing on different devices will end up with different sized images? I imagine the problem with resizing (as mentioned in another post) is that you could easily end up with format displacement. To avoid this you would have to measure the node.scrollwidth v the desire width and then shrink every item on the page accordingly.

**Comment by tsayen** [comment] 2016-03-09 11:07
Yes, generally the users on different devices might end up with different sizes of DOM "screenshots". This lib is written to make a screenshot look as close to the originally rendered DOM as possible, for a concrete client, but it can't make all the screenshots of your page in the world look exactly the same, because it's impossible.

**Comment by allenhwkim** [comment] 2016-03-29 17:29
Testing your script with stackoverflow, and it shows the following errors.

![image](https://cloud.githubusercontent.com/assets/1437734/14117286/fbc86088-f5b1-11e5-9212-3dd548104a9d.png)

Is there any workaround?

**Comment by tsayen** [comment] 2016-03-30 18:46
@allenhwkim as far as I know, there is no workaround to make your setup work exactly the way you want. The script should be served from the same domain as the images, otherwise it will not have access to images. Another way would be that CDN that serves those images would have to add something like `Access-Control-Allow-Origin: *` to response header, see [this article](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS)

**Comment by tsayen** [comment] 2016-03-30 18:48
I believe original issue was solved by [2.0.0](https://github.com/tsayen/dom-to-image/releases/tag/2.0.0), closing this for now

**Closed by tsayen** 2016-03-30 18:48 UTC
