### ISSUE TITLE
SVG image elements are not rasterized

### ISSUE THREAD

**Issue by egorodet** [tsayen/dom-to-image#71] opened 2016-10-02 18:02 UTC
### Use case: description

I'm trying to use dom-to-image library for converting JointJS diagrams to raster images (there is no standard way to do it, other than using commercial Rappid extensions). Dom-to-image works pretty well with JointJS, except one thing: it skips all images from rasterization. JointJS is using SVG image elements to draw images on diagram. As I found in dom-to-image source code, it supports only HTMLImageElement, while SVGImageElement type is just skipped. Could you please add support of SVG images to fully support rasterization of JointJS diagrams?

### Library version

2.5.1

### Browsers

- [x] Chrome 53.0.2785

**Comment by tsayen** [comment] 2016-10-03 10:04
Closing this as a duplicate of #39

**Closed by tsayen** 2016-10-03 10:04 UTC
