### ISSUE TITLE
Node with Image output image with borders

### ISSUE THREAD

**Issue by sdkcarlos** [tsayen/dom-to-image#14] opened 2015-11-11 17:55 UTC
First , Thanks for create such awesome library :dancers: 

I have found a bug when using it with a dom that contains a image (a border is added although it doesn't have a border property)

![asd](https://cloud.githubusercontent.com/assets/11634719/11098431/f59ac9c8-8872-11e5-904c-f0a0ff416948.png)

Thanks :D

**Comment by tsayen** [comment] 2015-11-12 06:45
Hi! Thanks for reporting. Could you please post the problematic image itself?

**Comment by sdkcarlos** [comment] 2015-11-12 15:19
Hey tsayen, thanks for the quick answer ! I solve this issue quickly changing the format of the image (was .jpg so i create a new version with transparency [png]).

However, the original jpg image didn't have border and I don't know why appears a border

**Comment by tsayen** [comment] 2015-11-18 11:54
The problem might also be because of the image scaling. Do you maybe set the image dimensions explicitly? I seem to recall some border-like artefacts showing on JPG as an effect of scaling.

**Comment by sdkcarlos** [comment] 2015-11-18 12:27
Yes, is a div which have a background image with explicit dimensions (height:100;width:100%;)

Thanks for the support

**Comment by tsayen** [comment] 2015-11-18 12:48
Do you observe those borders in the original html or is it just the rendered image?

**Comment by tsayen** [comment] 2015-11-18 14:46
I was trying to reproduce the issue with a test JPG image, but I can't (see here http://jsfiddle.net/tsayen/sark5r13/2/)  
If the issue is still bothering you, maybe you send me an example image (just attach it to the comment) that is rendered wrong.  
Or we can close this for now.  
What do you say?

**Comment by tsayen** [comment] 2015-11-27 06:18
closing this for now

**Closed by tsayen** 2015-11-27 06:18 UTC

**Comment by vmikhav** [comment] 2020-03-18 10:40
I had the same issue. I added `background-color: white;` CSS rule to the image parent node and it helped.

**Comment by Heriberto-Juarez** [comment] 2022-07-15 13:27
> I had the same issue. I added `background-color: white;` CSS rule to the image parent node and it helped.

I had problems with borders appearing out of nowhere in different nodes (div, and textarea) and this solved it. Thanks
